package FinalProject;

import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {

        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        unverseLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        debutLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        universeField = new javax.swing.JTextField();
        debutField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        videoPanel = new javax.swing.JPanel();
        gif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameTree = new javax.swing.JTree();
        selectField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        videoButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        characterComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        attackLengthField1 = new javax.swing.JTextField();
        attackDescField1 = new javax.swing.JTextField();
        attackNameField1 = new javax.swing.JTextField();
        animeLabel1 = new javax.swing.JLabel();
        attackDescLabel1 = new javax.swing.JLabel();
        attackLabel1 = new javax.swing.JLabel();
        gif2 = new javax.swing.JLabel();
        attackButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        stageComboBox = new javax.swing.JComboBox<>();
        maxPlayerField = new javax.swing.JTextField();
        animeLabel2 = new javax.swing.JLabel();
        attackDescLabel2 = new javax.swing.JLabel();
        universeNameField = new javax.swing.JTextField();
        stageNameField = new javax.swing.JTextField();
        attackLabel2 = new javax.swing.JLabel();
        stageImage = new javax.swing.JLabel();
        stageButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Smash Characters");

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 573));

        nameLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        unverseLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        unverseLabel.setText("Universe");

        descLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        descLabel.setText("Description");

        debutLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        debutLabel.setText("Debut");

        nameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameField.setFocusable(false);
        nameField.setPreferredSize(new java.awt.Dimension(180, 24));

        universeField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        universeField.setFocusable(false);
        universeField.setPreferredSize(new java.awt.Dimension(180, 24));

        debutField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        debutField.setFocusable(false);
        debutField.setPreferredSize(new java.awt.Dimension(180, 24));

        descField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descField.setFocusable(false);
        descField.setPreferredSize(new java.awt.Dimension(269, 140));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLabel)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(unverseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(debutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(debutField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(universeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unverseLabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(universeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debutLabel)
                    .addComponent(debutField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(descLabel)
                .addGap(8, 8, 8)
                .addComponent(descField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        jScrollPane2.setViewportView(jPanel4);

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/mario.gif"))); // NOI18N

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addComponent(gif)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addComponent(gif)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        nameTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        nameTree.setRootVisible(false);
        nameTree.getSelectionModel().setSelectionMode(javax.swing.tree.TreeSelectionModel.SINGLE_TREE_SELECTION);
        nameTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nameTree);

        selectField.setEditable(false);
        selectField.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Chaparral Pro Light", 1, 24)); // NOI18N
        jLabel2.setText("Character");

        selectButton.setText("Select");

        videoButton.setFont(new java.awt.Font("Chaparral Pro Light", 0, 24)); // NOI18N
        videoButton.setText("Video");
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(selectButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(selectField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(videoButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectButton)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(videoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Characters", jPanel1);

        characterComboBox.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        characterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Chaparral Pro Light", 1, 24)); // NOI18N
        jLabel3.setText("Character Selection");

        attackLengthField1.setEditable(false);
        attackLengthField1.setFocusable(false);

        attackDescField1.setEditable(false);
        attackDescField1.setFocusable(false);

        attackNameField1.setEditable(false);
        attackNameField1.setFocusable(false);

        animeLabel1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        animeLabel1.setText("Animation Length");

        attackDescLabel1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        attackDescLabel1.setText("Description");

        attackLabel1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        attackLabel1.setText("Attack Name");

        attackButton.setText("Select");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(characterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(animeLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(attackLengthField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attackLabel1)
                                    .addComponent(attackDescLabel1))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attackNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attackDescField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(attackButton))
                        .addGap(40, 40, 40)
                        .addComponent(gif2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(characterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attackLabel1)
                            .addComponent(attackNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attackDescField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attackDescLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attackLengthField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animeLabel1))
                        .addGap(29, 29, 29)
                        .addComponent(attackButton))
                    .addComponent(gif2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Attack", jPanel2);

        jLabel4.setFont(new java.awt.Font("Chaparral Pro Light", 1, 24)); // NOI18N
        jLabel4.setText("Stage Selection");

        stageComboBox.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        stageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        maxPlayerField.setEditable(false);
        maxPlayerField.setFocusable(false);

        animeLabel2.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        animeLabel2.setText("Max Players");

        attackDescLabel2.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        attackDescLabel2.setText("Universe");

        universeNameField.setEditable(false);
        universeNameField.setFocusable(false);

        stageNameField.setEditable(false);
        stageNameField.setFocusable(false);

        attackLabel2.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        attackLabel2.setText("Stage Name");

        stageButton.setText("Select");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(animeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(attackLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(attackDescLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(universeNameField)
                                        .addComponent(stageNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(maxPlayerField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(stageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stageButton))
                        .addGap(18, 18, 18)
                        .addComponent(stageImage, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(stageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attackLabel2)
                            .addComponent(stageNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attackDescLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(universeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animeLabel2))
                        .addGap(44, 44, 44)
                        .addComponent(stageButton))
                    .addComponent(stageImage, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stages", jPanel3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/smash.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed

    }//GEN-LAST:event_videoButtonActionPerformed

    private void nameTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTreeMouseClicked
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) nameTree.getSelectionPath().getLastPathComponent();
        selectField.setText(selectedNode.getUserObject().toString());
    }//GEN-LAST:event_nameTreeMouseClicked

    //_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
    public void selectButtonListener(ActionListener a) {  //<<<<<<<<<<<<<<<<<<<<<<< Select Button
        selectButton.addActionListener(a);
    }

    public void videoButtonListener(ActionListener a) {   //<<<<<<<<<<<<<<<<<<<<<<< Video Button
        videoButton.addActionListener(a);
    }

    public void setTreeModel(DefaultTreeModel n) {
        nameTree.setModel(n);
    }
    
    public void attackButtonListener(ActionListener a) {
        attackButton.addActionListener(a);
    }
    
    public void stageButtonListener(ActionListener a) {
        stageButton.addActionListener(a);
    }

    //Character Tab Get-Set Methods------------------------------------
    public void setVideo(String url) {
        videoFrame v = new videoFrame();
        v.init(url);
    }

    public String getName() {
        return selectField.getText();
    }
    
    public javax.swing.JTree getTree() {
        return nameTree;
    }

    public void setName(String name) {
        nameField.setText(name);
    }

    public void setUniverse(String universe) {
        universeField.setText(universe);
    }

    public void setDebut(String debut) {
        debutField.setText(debut);
    }

    public void setDescription(String desc) {
        descField.setText(desc);
    }

    public void setImage(String dir) {
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(dir).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        image.setIcon(imageIcon);
        //image.setIcon(new javax.swing.ImageIcon("D:\\smash.png"));
    }

    public void setGIF(String dir) {
        gif.setIcon(new javax.swing.ImageIcon(dir));

    }

    //END -------------------------------------------------------------
    //Attack Tab Get-Set Methods---------------------------------------
    public void setAttack(String attack) {
        attackNameField1.setText(attack);
    }

    public void setAttackDescription(String d) {
        attackDescField1.setText(d);
    }

    public void setAttackLength(String l) {
        attackLengthField1.setText(l);
    }

    public void setAttackGIF(String dir) {
        gif2.setIcon(new javax.swing.ImageIcon(dir));

    }

    public void setCharacterComboBoxModel(DefaultComboBoxModel m) {
        getCharacterComboBox().setModel(m);
    }

    public javax.swing.JComboBox<String> getCharacterComboBox() {
        return characterComboBox;
    }
    
    public javax.swing.JButton getAttackButton() {
        return attackButton;
    }
    //END--------------------------------------------------------------

    
    
    //Stage Tab Get-Set Methods---------------------------------------
    public void setStage(String stage) {
        stageNameField.setText(stage);
    }

    public void setUniverseName(String u) {
        universeNameField.setText(u);
    }

    public void setMaxPlayer(String mp) {
        maxPlayerField.setText(mp);
    }

    public void setStageImage(String dir) {
        stageImage.setIcon(new javax.swing.ImageIcon(dir));

    }

    public void setStageComboBoxModel(DefaultComboBoxModel m) {
        getStageComboBox().setModel(m);
    }

    public javax.swing.JComboBox<String> getStageComboBox() {
        return stageComboBox;
    }
    //END--------------------------------------------------------------

    //_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animeLabel1;
    private javax.swing.JLabel animeLabel2;
    private javax.swing.JButton attackButton;
    private javax.swing.JTextField attackDescField1;
    private javax.swing.JLabel attackDescLabel1;
    private javax.swing.JLabel attackDescLabel2;
    private javax.swing.JLabel attackLabel1;
    private javax.swing.JLabel attackLabel2;
    private javax.swing.JTextField attackLengthField1;
    private javax.swing.JTextField attackNameField1;
    private javax.swing.JComboBox<String> characterComboBox;
    private javax.swing.JTextField debutField;
    private javax.swing.JLabel debutLabel;
    private javax.swing.JTextField descField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel gif2;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maxPlayerField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTree nameTree;
    private javax.swing.JButton selectButton;
    private javax.swing.JTextField selectField;
    private javax.swing.JButton stageButton;
    private javax.swing.JComboBox<String> stageComboBox;
    private javax.swing.JLabel stageImage;
    private javax.swing.JTextField stageNameField;
    private javax.swing.JTextField universeField;
    private javax.swing.JTextField universeNameField;
    private javax.swing.JLabel unverseLabel;
    private javax.swing.JButton videoButton;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
